apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: gkamalakar06/devops-client:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: client

